apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dashboard
  name: dasshboard-service
spec:
  ports:
    - name: dashboardservice
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: dashboard
  type: NodePort
